### ISSUE TITLE
Unable to extract features with version 0.3.7

### ISSUE THREAD

**Issue by wintermute221** [salan668/FAE#61]
Hi, I'm using FAE (V.0.3.7) on a Mac and I want to firstly extract features from some medical images.

But the interface in this version is slightly different from the previous version (also different from that in the video where you presented the version)

When I want to add a specified file(like a ROI file) there will a window popping up reminding that:

'ShowName patterns are used add pre-name in the feature matrix.'

I wonder what should I do with that problem? Many thanks.

**Comment by salan668** [comment]
Hi, sorry that we don't have a Mac and can't test the layout of the interface on the Mac. The reason that the interface of the Feature Extraction is differnt from that in the video, is we updated the interface to make it more clearly. However, we does not udpate the coding implement totally. To do with your problem templerately, maybe you could type any words, such as "123" in the text box behind "Modality / Series". Then I believe you could extract the features. 

Thank you for pointing the bugs here and we will solve it soon. 

Thanks for using FAE.

**Comment by salan668** [comment]
@wintermute221 We updated the code to fixing the bug of your descirption. Now you could add the ROI pattern without adding the Name description.

**Comment by wintermute221** [comment]
@salan668 Many thanks for your help. I have already solved the problem by filling 'Modality/Series' with a name such as 'Image'. In this way specified files could be added. 

Besides, thank you for letting me know the update. Really appreciate your time.
