### ISSUE TITLE
conflicting dependencies

### ISSUE THREAD

**Issue by radiomic** [salan668/FAE#63]
Could you please check the dependency list and provide explanations about how to install the program? Exe version works good. But cannot perform hyperparameter tunign.

**Comment by salan668** [comment]
Hi, How did you perfrom hyper-parameters? Used the souce code, or the exe version? the hyper-parameters were griding-searched according to the json config file and only used the hyper-parameter which got the highest AUC on the cross validation data set.

**Comment by salan668** [comment]
Nope, pyinstaller only works if you would like to release the software.
Exe version does not store the best candidate combiantion of the feature selection. Try to use the source code and PyWavelet -- 1.1.1. and used the updates pyradiomics.

**Comment by radiomic** [comment]
Thanks. Have a couple of questions as well.

(fae) C:\Users\xxx\Desktop\FAE>python MainFrameCall.py
Traceback (most recent call last):
  File "MainFrameCall.py", line 3, in <module>
    from HomeUI.HomePageForm import HomePageForm
  File "C:\Users\xxx\Desktop\FAE\HomeUI\HomePageForm.py", line 10, in <module>
    from HomeUI.HomePage import Ui_HomePage
ModuleNotFoundError: No module named 'HomeUI.HomePage'

>>> I have this error when I call MainFrameCall.py
is this about .ui to .py conversion? How can we convert them?
is that possinble to share the version converted? it would be much easier to use by everybody.
Can you please provide the source code and step by step instructions how to install and start to use?
Thanks.

**Comment by salan668** [comment]
If you use PyQt5, there is a tool named "pyuic“ to convert a .ui file to
the corresponding .py file.

**Comment by radiomic** [comment]
> 

Should we convert ALL .ui's to .py?

(fae) C:\Users\xxx\Desktop\FAE>dir /s /b *.ui

C:\Users\xxx\Desktop\FAE\BC\GUI\Prepare.ui
C:\Users\xxx\Desktop\FAE\BC\GUI\Process.ui
C:\Users\xxx\Desktop\FAE\BC\GUI\Visualization.ui
C:\Users\xxx\Desktop\FAE\Feature\GUI\FeatureExtraction2.ui
C:\Users\xxx\Desktop\FAE\Feature\GUI\FeatureMerge.ui
C:\Users\xxx\Desktop\FAE\HomeUI\HomePage.ui
C:\Users\xxx\Desktop\FAE\SA\GUI\Prepare.ui
C:\Users\xxx\Desktop\FAE\SA\GUI\Process.ui
C:\Users\xxx\Desktop\FAE\SA\GUI\Visualization.ui

**Comment by salan668** [comment]
Sure, you have to convert all of them.

**Comment by radiomic** [comment]
(fae) C:\Users\xxx\Desktop\test\FAE>pip install -r req.txt
Collecting imbalanced-learn==0.6.2
  Using cached imbalanced_learn-0.6.2-py3-none-any.whl (163 kB)
Collecting matplotlib==3.2.0
  Using cached matplotlib-3.2.0-cp37-cp37m-win_amd64.whl (9.2 MB)
Collecting numpy==1.18.1
  Using cached numpy-1.18.1-cp37-cp37m-win_amd64.whl (12.8 MB)
Collecting pandas==1.0.1
  Using cached pandas-1.0.1-cp37-cp37m-win_amd64.whl (9.0 MB)
Collecting pdfdocument==3.3
  Using cached pdfdocument-3.3.tar.gz (9.0 kB)
  Preparing metadata (setup.py) ... done
Collecting pillow==7.0.0
  Using cached Pillow-7.0.0-cp37-cp37m-win_amd64.whl (2.0 MB)
Collecting PyQt5==5.14.1
  Using cached PyQt5-5.14.1-5.14.1-cp35.cp36.cp37.cp38-none-win_amd64.whl (53.1 MB)
Collecting PyQtGraph==0.10.0
  Using cached pyqtgraph-0.10.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pyradiomics==3.0 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from -r req.txt (line 9)) (3.0)
Collecting reportlab==3.5.34
  Using cached reportlab-3.5.34-cp37-cp37m-win_amd64.whl (2.3 MB)
Collecting scikit-learn==0.22.2
  Using cached scikit_learn-0.22.2-cp37-cp37m-win_amd64.whl (6.5 MB)
Collecting scikit-image==0.18.3
  Using cached scikit_image-0.18.3-cp37-cp37m-win_amd64.whl (12.1 MB)
Collecting scipy==1.4.1
  Using cached scipy-1.4.1-cp37-cp37m-win_amd64.whl (30.9 MB)
Collecting seaborn==0.10.0
  Using cached seaborn-0.10.0-py3-none-any.whl (215 kB)
Requirement already satisfied: statsmodels==0.11.1 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from -r req.txt (line 15)) (0.11.1)
Collecting trimesh==3.9.29
  Using cached trimesh-3.9.29-py3-none-any.whl (635 kB)
Requirement already satisfied: joblib>=0.11 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from imbalanced-learn==0.6.2->-r req.txt (line 1)) (0.16.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from matplotlib==3.2.0->-r req.txt (line 2)) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from matplotlib==3.2.0->-r req.txt (line 2)) (0.10.0)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from matplotlib==3.2.0->-r req.txt (line 2)) (1.2.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from matplotlib==3.2.0->-r req.txt (line 2)) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from pandas==1.0.1->-r req.txt (line 4)) (2020.1)
Requirement already satisfied: PyQt5-sip<13,>=12.7 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from PyQt5==5.14.1->-r req.txt (line 7)) (12.9.0)
Requirement already satisfied: six>=1.10.0 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from pyradiomics==3.0->-r req.txt (line 9)) (1.15.0)
Requirement already satisfied: SimpleITK>=0.9.1 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from pyradiomics==3.0->-r req.txt (line 9)) (1.2.4)
Requirement already satisfied: pykwalify>=1.6.0 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from pyradiomics==3.0->-r req.txt (line 9)) (1.7.0)
Requirement already satisfied: PyWavelets<=1.0.0,>=0.4.0 in c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages (from pyradiomics==3.0->-r req.txt (line 9)) (1.0.0)
INFO: pip is looking at multiple versions of scikit-learn to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of reportlab to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyradiomics to determine which version is compatible with other requirements. This could take a while.
Collecting pyradiomics==3.0
  Using cached pyradiomics-3.0-cp37-cp37m-win_amd64.whl (121 kB)
INFO: pip is looking at multiple versions of pyqtgraph to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pyqt5 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pillow to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pdfdocument to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pandas to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of numpy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of matplotlib to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of imbalanced-learn to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r req.txt (line 12) and -r req.txt (line 9) because these package versions have conflicting dependencies.

The conflict is caused by:
    pyradiomics 3.0 depends on PyWavelets<=1.0.0 and >=0.4.0
    scikit-image 0.18.3 depends on PyWavelets>=1.1.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by radiomic** [comment]
still have problem. 

by the way converted all uis to py with the following code

FOR /F "tokens=*" %G IN ('dir /s /b *.ui'); DO cd %~pG & python -m PyQt5.uic.pyuic -x %~nxG -o %~nG.py

**Comment by radiomic** [comment]
Can you please the conda or pip code for all requirements. I use your prerequisites just below.

imbalanced-learn==0.6.2
matplotlib==3.2.0
numpy==1.18.1
pandas==1.0.1
pdfdocument==3.3
pillow==7.0.0
PyQt5==5.14.1
PyQtGraph==0.10.0
pyradiomics==3.0
reportlab==3.5.34
scikit-learn==0.22.2
scikit-image==0.18.3
scipy==1.4.1
seaborn==0.10.0
statsmodels==0.11.1
trimesh==3.9.29

**Comment by radiomic** [comment]
Solved the problem. Anyone having problem can use the following conda environment package list to create the environment to run the application.

1. Copy the following text to a .txt file. Name it as pkgs.txt.

# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2022.3.29-haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2021.4.0-haa95532_3556.conda
https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cpu.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.27.29016-h5e58377_2.conda
https://conda.anaconda.org/pytorch/noarch/cpuonly-2.0-0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/mkl-2021.4.0-haa95532_640.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.2-h21ff451_1.conda
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9d-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libuv-1.40.0-he774522_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-1.2.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/lz4-c-1.9.3-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-1.1.1n-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.38.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tk-8.6.11-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/xz-5.2.5-h62dcd97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.11-hbd8134f_5.conda
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.37-h2a8f88b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/python-3.7.6-h60c2a47_2.conda
https://repo.anaconda.com/pkgs/main/win-64/zstd-1.4.9-h19a0ad4_0.conda
https://repo.anaconda.com/pkgs/main/win-64/certifi-2021.10.8-py37haa95532_2.conda
https://repo.anaconda.com/pkgs/main/noarch/charset-normalizer-2.0.4-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/freetype-2.10.4-hd328e21_0.conda
https://repo.anaconda.com/pkgs/main/noarch/idna-3.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libtiff-4.2.0-hd0e1b90_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.21-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/typing_extensions-4.1.1-pyh06a4308_0.conda
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.37.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/win_inet_pton-1.1.0-py37haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wincertstore-0.2-py37haa95532_2.conda
https://repo.anaconda.com/pkgs/main/win-64/cffi-1.15.0-py37h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.4.0-py37h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pillow-9.0.1-py37hdc2b20a_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pysocks-1.7.1-py37_1.conda
https://conda.anaconda.org/pytorch/win-64/pytorch-1.11.0-py3.7_cpu_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/setuptools-61.2.0-py37haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/brotlipy-0.7.0-py37h2bbff1b_1003.conda
https://repo.anaconda.com/pkgs/main/win-64/cryptography-36.0.0-py37h21b164f_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.21.5-py37hca35cd5_1.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-21.2.4-py37haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pyopenssl-22.0.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/urllib3-1.26.8-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/requests-2.27.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.3.1-py37h277e83a_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.2.2-py37hf11a4ad_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.21.5-py37h7a0a035_1.conda
https://conda.anaconda.org/pytorch/win-64/torchaudio-0.11.0-py37_cpu.tar.bz2
https://conda.anaconda.org/pytorch/win-64/torchvision-0.12.0-py37_cpu.tar.bz2

2. >>> conda create --name NEWENV --file pkgs.txt
3. activate the environment with >>> conda activate NEWENV
4. Go to software folder
5. type to cmdline >>> python MainFrameCall.py

**Comment by radiomic** [comment]
However, still cannot reach hyperparameter tuning results? How can we obtain the best hyperparameters to report?

**Comment by salan668** [comment]
Thank you to provide the dependent packages.

**Comment by radiomic** [comment]
> > However, still cannot reach hyperparameter tuning results? How can we obtain the best hyperparameters to report?
> 
> OMG. I added the hyper-paramter grid-searching in the previouse verison, such as 0.3.7. But I changed the pipeline structure of the model development. So the hyper-parameter was not added yet. Sorry for that and I will add it in the following version.

Thank you very much.
